In [19]:
import sf_project.settings as settings
import pandas as pd
import importlib
import sf_project.strategy as strategy
import sf_project.plots_statistics as plots

In [20]:
#LOAD DATA
DATA_DIR = settings.ROOT / "sf_project" / "data"
data_in = pd.read_parquet( DATA_DIR / "prices_in_sample.parquet")
data_w_contract_id = pd.read_parquet(DATA_DIR / "prices_in_sample_w_contract_id.parquet")
data_out = pd.read_parquet(DATA_DIR / "prices_out_of_sample.parquet")
data_w_contract_id_out = pd.read_parquet(DATA_DIR / "prices_out_of_sample_w_contract_id.parquet")
bid_ask_in = pd.read_parquet(DATA_DIR / "bidask_in_sample.parquet")
bid_ask_out = pd.read_parquet(DATA_DIR / "bidask_out_of_sample.parquet")

In [29]:
open_until = settings.open_until
close_until = settings.close_time_limit
contracts = settings.BEST_PREDICTORS.keys()
dict_thresholds = settings.BEST_PREDICTORS

In [30]:
#IN SAMPLE TRADES - MULTI ENTRY
prediction_path = DATA_DIR / "predictions" / "predictions_in_sample"
trades_in = strategy.run_multiple_contracts(data_in, bid_ask_in, contracts, dict_thresholds, open_until, close_until, prediction_path)
trades_in.to_parquet(settings.ROOT / "sf_project" / "data" / "trades" / "trades_in_sample.parquet")

Processing GAS_M_1...
Processing GAS_M_2...
Processing EM_M_1...

/Users/filipekrt/PycharmProjects/EnergyTrading/sf_project/strategy.py:275: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(all_trades, ignore_index=True) if all_trades else pd.DataFrame()

Processing QY_2...

/Users/filipekrt/PycharmProjects/EnergyTrading/sf_project/strategy.py:275: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(all_trades, ignore_index=True) if all_trades else pd.DataFrame()

Processing QY_3...

/Users/filipekrt/PycharmProjects/EnergyTrading/sf_project/strategy.py:275: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(all_trades, ignore_index=True) if all_trades else pd.DataFrame()

Processing QY_4...
Processing QY_5...

/Users/filipekrt/PycharmProjects/EnergyTrading/sf_project/strategy.py:275: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(all_trades, ignore_index=True) if all_trades else pd.DataFrame()

Processing Y_2...

/Users/filipekrt/PycharmProjects/EnergyTrading/sf_project/strategy.py:275: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(all_trades, ignore_index=True) if all_trades else pd.DataFrame()

Processing M_2...

/Users/filipekrt/PycharmProjects/EnergyTrading/sf_project/strategy.py:275: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(all_trades, ignore_index=True) if all_trades else pd.DataFrame()

Processing M_3...

/Users/filipekrt/PycharmProjects/EnergyTrading/sf_project/strategy.py:275: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(all_trades, ignore_index=True) if all_trades else pd.DataFrame()

Processing M_4...
Processing M_5...
Processing IT_M_1...
Processing IT_QY_1...

In [31]:
#OUT-OF-SAMPLE TRADES - MULTI ENTRY
prediction_path = DATA_DIR / "predictions" / "predictions_out_of_sample"
trades_out = strategy.run_multiple_contracts(data_out, bid_ask_out, contracts, dict_thresholds, open_until, close_until, prediction_path)
trades_out.to_parquet(settings.ROOT / "sf_project" / "data" / "trades" / "trades_out_of_sample.parquet")

Processing GAS_M_1...
Processing GAS_M_2...
Processing EM_M_1...
Processing QY_2...
Processing QY_3...
Processing QY_4...
Processing QY_5...
Processing Y_2...
Processing M_2...
Processing M_3...
Processing M_4...
Processing M_5...
Processing IT_M_1...
Processing IT_QY_1...

In [32]:
plots.calculate_total_pnl(trades_out)

                    PnL
EM_M_1     11319.667283
GAS_M_1     1493.649492
GAS_M_2      -30.148574
M_1            0.000000
M_2        23317.305501
M_3        10483.040429
M_4         2322.218446
M_5          -46.929680
IT_M_1      5611.908512
QY_1           0.000000
QY_2       22668.367168
QY_3       -5248.682337
QY_4        5263.111059
QY_5        -215.026857
QY_6           0.000000
IT_QY_1     1751.664104
Y_1            0.000000
Y_2        19728.945819
Total_PnL  98419.090364

In [33]:
plots.calculate_total_pnl(trades_in)

                     PnL
EM_M_1      19527.022144
GAS_M_1     13474.607117
GAS_M_2      9985.044044
M_1             0.000000
M_2         18462.924786
M_3         -6040.999500
M_4          8746.403273
M_5          -713.466747
IT_M_1      19277.330769
QY_1            0.000000
QY_2        76316.775505
QY_3        52801.869008
QY_4        38346.503389
QY_5        30198.602144
QY_6            0.000000
IT_QY_1     49397.179145
Y_1             0.000000
Y_2        128394.064494
Total_PnL  458173.859573

In [34]:
#SINGLE- ENTRY - IN SAMPLE
#Zde jen pro jednoduchost nastav threshold 0.1 pro všechny
dict = {}
for target_col in contracts:
    dict[target_col] = 0.2
prediction_path = "/Users/filipekrt/SF/Ekrt/sf_project/predictions_in_sample"
single_trades_in = strategy.run_multiple_contracts(data_in, bid_ask_in, contracts, dict, open_until, close_until, prediction_path)

Processing GAS_M_1...
Processing GAS_M_2...
Processing EM_M_1...

/Users/filipekrt/PycharmProjects/EnergyTrading/sf_project/strategy.py:275: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(all_trades, ignore_index=True) if all_trades else pd.DataFrame()

Processing QY_2...

/Users/filipekrt/PycharmProjects/EnergyTrading/sf_project/strategy.py:275: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(all_trades, ignore_index=True) if all_trades else pd.DataFrame()

Processing QY_3...

/Users/filipekrt/PycharmProjects/EnergyTrading/sf_project/strategy.py:275: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(all_trades, ignore_index=True) if all_trades else pd.DataFrame()

Processing QY_4...
Processing QY_5...

/Users/filipekrt/PycharmProjects/EnergyTrading/sf_project/strategy.py:275: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(all_trades, ignore_index=True) if all_trades else pd.DataFrame()

Processing Y_2...

/Users/filipekrt/PycharmProjects/EnergyTrading/sf_project/strategy.py:275: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(all_trades, ignore_index=True) if all_trades else pd.DataFrame()
/Users/filipekrt/PycharmProjects/EnergyTrading/sf_project/strategy.py:275: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(all_trades, ignore_index=True) if all_trades else pd.DataFrame()

Processing M_2...
Processing M_3...

/Users/filipekrt/PycharmProjects/EnergyTrading/sf_project/strategy.py:275: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(all_trades, ignore_index=True) if all_trades else pd.DataFrame()

Processing M_4...
Processing M_5...
Processing IT_M_1...
Processing IT_QY_1...

In [35]:
#####LOAD TRADES
trades_in_sample = pd.read_parquet(DATA_DIR / "trades" / "trades_in_sample.parquet")
trades_out_of_sample = pd.read_parquet(DATA_DIR / "trades" / "trades_out_of_sample.parquet")

In [36]:
plots.calculate_total_pnl(trades_in_sample)

                     PnL
EM_M_1      19527.022144
GAS_M_1     13474.607117
GAS_M_2      9985.044044
M_1             0.000000
M_2         18462.924786
M_3         -6040.999500
M_4          8746.403273
M_5          -713.466747
IT_M_1      19277.330769
QY_1            0.000000
QY_2        76316.775505
QY_3        52801.869008
QY_4        38346.503389
QY_5        30198.602144
QY_6            0.000000
IT_QY_1     49397.179145
Y_1             0.000000
Y_2        128394.064494
Total_PnL  458173.859573

In [37]:
plots.calculate_total_pnl(trades_out_of_sample)

                    PnL
EM_M_1     11319.667283
GAS_M_1     1493.649492
GAS_M_2      -30.148574
M_1            0.000000
M_2        23317.305501
M_3        10483.040429
M_4         2322.218446
M_5          -46.929680
IT_M_1      5611.908512
QY_1           0.000000
QY_2       22668.367168
QY_3       -5248.682337
QY_4        5263.111059
QY_5        -215.026857
QY_6           0.000000
IT_QY_1     1751.664104
Y_1            0.000000
Y_2        19728.945819
Total_PnL  98419.090364

In [38]:
trades_out_of_sample

,threshold,contract,day,trade_type,t_open,t_close,entry_price,close_price,new_opened,total_opened_for_now,pnl
0,0.050,GAS_M_1,2025-10-02,Short,2025-10-02 08:12:00+02:00,2025-10-02 11:00:00+02:00,16.639999,16.291491,1,1,0.348508
1,0.075,GAS_M_1,2025-10-06,Short,2025-10-06 09:30:00+02:00,2025-10-06 11:00:00+02:00,17.630001,17.575400,2,2,0.109201
2,0.050,GAS_M_1,2025-10-09,Long,2025-10-09 08:19:00+02:00,2025-10-09 11:00:00+02:00,17.110001,17.255712,1,1,0.145711
3,0.050,GAS_M_1,2025-10-10,Short,2025-10-10 08:07:00+02:00,2025-10-10 11:00:00+02:00,17.224998,16.947016,1,1,0.277982
4,0.050,GAS_M_1,2025-10-13,Short,2025-10-13 09:00:00+02:00,2025-10-13 11:00:00+02:00,16.795000,16.809440,1,1,-0.014440
...,...,...,...,...,...,...,...,...,...,...,...
547,0.350,IT_M_1,2025-12-18,Short,2025-12-18 08:53:00+01:00,2025-12-18 11:00:00+01:00,84.059998,84.350161,1,1,-0.290163
548,0.350,IT_QY_1,2025-11-21,Short,2025-11-21 09:01:00+01:00,2025-11-21 11:00:00+01:00,81.160004,81.053996,1,1,0.106007
549,0.525,IT_QY_1,2025-11-21,Short,2025-11-21 09:04:00+01:00,2025-11-21 11:00:00+01:00,81.400002,81.053996,1,2,0.346005
550,0.350,IT_QY_1,2025-12-15,Short,2025-12-15 09:26:00+01:00,2025-12-15 11:00:00+01:00,79.139999,79.041054,1,1,0.098945
551,0.350,IT_QY_1,2025-12-17,Long,2025-12-17 09:29:00+01:00,2025-12-17 11:00:00+01:00,78.860001,79.119999,1,1,0.259998